### ISSUE TITLE
Add `new` command

### ISSUE THREAD

**Issue by c-rus** [c-rus/orbit#3]
## Big Idea

The `new` command is used to create a blank project ready to be used with Orbit. It sets up a boiler-plate file structure and a simple manifest.

## Details
It's main argument is a fully qualified `pkgid`. This gives Orbit the vendor, library, and name of the new project to include into the manifest. Orbit will create a new folder, a manifest, and set up version control.

## Examples
```
$ orbit new uf-ece.rary.gates
```

## Roadmap
- [ ] create a `pkgid` struct to support verifying valid package identifiers
- [ ] create `version` struct to support verifying valid versions in manifest
- [ ] create `manifest` file parser to be able to write basic manifest
- [ ] create basic `project` struct to handle setting up new folders
